version: '3.8'

services:
  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: weather-app-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY:-your_api_key_here}
    restart: unless-stopped
    networks:
      - weather-app-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Service (to be added after frontend development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: weather-app-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - weather-app-network

networks:
  weather-app-network:
    driver: bridge

volumes:
  backend-node-modules:
  frontend-node-modules:
