version: '3.8'

services:
  # Backend Service
  backend:
    image: deepdey01/weather-app-backend:latest
    container_name: weather-app-backend-test
    ports:
      - "5001:5000"  # Use different port to avoid conflict with registry
    environment:
      - NODE_ENV=production
      - PORT=5000
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY:-your_api_key_here}
    restart: unless-stopped
    networks:
      - weather-app-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Service
  frontend:
    image: deepdey01/weather-app-frontend:latest
    container_name: weather-app-frontend-test
    ports:
      - "3001:80"  # Use different port, nginx listens on 80 internally
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - weather-app-network

networks:
  weather-app-network:
    driver: bridge
